import { colors } from "./tokens/tokens";
import { StyleSheet } from "react-native";

export const petmapStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.wine,
  },
  map: {
    flex: 1,
  },
  // ── Header sobreposto ao mapa ──
  header: {
    position: "absolute",
    top: 52,
    left: 16,
    right: 16,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    zIndex: 10,
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: colors.wine,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 5,
  },
  backButtonText: {
    color: colors.cream,
    fontSize: 22,
    fontWeight: "900",
    lineHeight: 24,
  },
  headerTitleBox: {
    flex: 1,
    backgroundColor: colors.wine,
    borderRadius: 20,
    paddingHorizontal: 16,
    paddingVertical: 10,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 5,
  },
  headerTitle: {
    color: colors.cream,
    fontSize: 16,
    fontWeight: "900",
  },
  headerSubtitle: {
    color: colors.cream,
    fontSize: 11,
    opacity: 0.7,
    marginTop: 1,
  },
  // ── FAB ──
  fab: {
    position: "absolute",
    bottom: 32,
    right: 20,
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: colors.terracotta,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.35,
    shadowRadius: 6,
    elevation: 8,
  },
  fabText: {
    color: "#fff",
    fontSize: 28,
    fontWeight: "900",
    lineHeight: 32,
  },
  // ── Loading / empty overlay ──
  overlay: {
    ...StyleSheet.absoluteFillObject,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(123, 30, 46, 0.6)",
  },
  overlayText: {
    color: colors.cream,
    marginTop: 12,
    fontSize: 14,
    fontWeight: "700",
  },
  // ── Modal de detalhes do pin ──
  modalBackdrop: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "flex-end",
  },
  detailCard: {
    backgroundColor: colors.cardBg,
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    padding: 24,
    paddingBottom: 40,
  },
  detailHandle: {
    width: 40,
    height: 4,
    borderRadius: 2,
    backgroundColor: "rgba(245, 236, 215, 0.3)",
    alignSelf: "center",
    marginBottom: 20,
  },
  detailEmoji: {
    fontSize: 36,
    textAlign: "center",
    marginBottom: 8,
  },
  detailName: {
    fontSize: 22,
    fontWeight: "900",
    color: colors.cream,
    textAlign: "center",
  },
  detailAddress: {
    fontSize: 13,
    color: colors.cream,
    opacity: 0.7,
    textAlign: "center",
    marginTop: 6,
    lineHeight: 18,
  },
  detailButtonRow: {
    flexDirection: "row",
    gap: 12,
    marginTop: 24,
  },
  directionsButton: {
    flex: 1,
    height: 52,
    borderRadius: 999,
    backgroundColor: colors.terracotta,
    alignItems: "center",
    justifyContent: "center",
  },
  directionsButtonText: {
    color: "#fff",
    fontWeight: "900",
    fontSize: 15,
  },
  closeButton: {
    height: 52,
    paddingHorizontal: 20,
    borderRadius: 999,
    borderWidth: 2,
    borderColor: "rgba(245, 236, 215, 0.35)",
    alignItems: "center",
    justifyContent: "center",
  },
  closeButtonText: {
    color: colors.cream,
    fontWeight: "800",
    fontSize: 14,
  },
  // ── Modal de adicionar local ──
  addModalBackdrop: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "flex-end",
  },
  addCard: {
    backgroundColor: colors.cardBg,
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    padding: 24,
    paddingBottom: 40,
  },
  addHandle: {
    width: 40,
    height: 4,
    borderRadius: 2,
    backgroundColor: "rgba(245, 236, 215, 0.3)",
    alignSelf: "center",
    marginBottom: 20,
  },
  addTitle: {
    fontSize: 20,
    fontWeight: "900",
    color: colors.cream,
    marginBottom: 4,
  },
  addSubtitle: {
    fontSize: 13,
    color: colors.cream,
    opacity: 0.65,
    marginBottom: 20,
    lineHeight: 18,
  },
  geocodeResultBox: {
    backgroundColor: "rgba(45, 122, 79, 0.2)",
    borderRadius: 14,
    padding: 12,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: colors.greenOk,
  },
  geocodeResultLabel: {
    color: colors.greenOk,
    fontWeight: "800",
    fontSize: 11,
    textTransform: "uppercase",
    letterSpacing: 0.6,
    marginBottom: 4,
  },
  geocodeResultText: {
    color: colors.cream,
    fontSize: 12,
    lineHeight: 17,
    opacity: 0.85,
  },
  geocodeErrorBox: {
    backgroundColor: "rgba(255, 107, 107, 0.15)",
    borderRadius: 14,
    padding: 12,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: colors.statusError,
  },
  geocodeErrorText: {
    color: colors.statusError,
    fontSize: 13,
    fontWeight: "700",
  },
  searchButton: {
    height: 48,
    borderRadius: 999,
    borderWidth: 2,
    borderColor: colors.cream,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 12,
  },
  searchButtonText: {
    color: colors.cream,
    fontWeight: "800",
    fontSize: 14,
  },
  addButtonRow: {
    flexDirection: "row",
    gap: 12,
    marginTop: 4,
  },
  saveButton: {
    flex: 1,
    height: 52,
    borderRadius: 999,
    backgroundColor: colors.cream,
    alignItems: "center",
    justifyContent: "center",
  },
  saveButtonText: {
    color: colors.wine,
    fontWeight: "900",
    fontSize: 15,
  },
  saveButtonDisabled: {
    opacity: 0.4,
  },
  cancelButton: {
    height: 52,
    paddingHorizontal: 20,
    borderRadius: 999,
    borderWidth: 2,
    borderColor: "rgba(245, 236, 215, 0.35)",
    alignItems: "center",
    justifyContent: "center",
  },
  cancelButtonText: {
    color: colors.cream,
    fontWeight: "800",
    fontSize: 14,
  },
  // ── Feedback modal ──
  feedbackBackdrop: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.55)",
    alignItems: "center",
    justifyContent: "center",
  },
  feedbackCard: {
    backgroundColor: colors.cardBg,
    borderRadius: 24,
    padding: 28,
    alignItems: "center",
    width: "80%",
  },
  feedbackIcon: {
    fontSize: 40,
    marginBottom: 12,
  },
  feedbackIconSuccess: {
    color: colors.statusSuccess,
  },
  feedbackIconError: {
    color: colors.statusError,
  },
  feedbackTitle: {
    color: colors.cream,
    fontSize: 18,
    fontWeight: "900",
    marginBottom: 8,
    textAlign: "center",
  },
  feedbackMessage: {
    color: colors.cream,
    opacity: 0.75,
    fontSize: 13,
    textAlign: "center",
    lineHeight: 18,
    marginBottom: 20,
  },
  feedbackButton: {
    paddingHorizontal: 32,
    height: 46,
    borderRadius: 999,
    backgroundColor: colors.cream,
    alignItems: "center",
    justifyContent: "center",
  },
  feedbackButtonText: {
    color: colors.wine,
    fontWeight: "900",
    fontSize: 14,
  },
});
