import { StyleSheet } from "react-native";

const stylesColors = {
  wine: "#7B1E2E",
  wineDark: "#4A1020",
  wineLight: "#9B2E42",
  cardBg: "#8B2535",
  cream: "#F5ECD7",
  white: "#FFFFFF",
};

export const settingsStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: stylesColors.wine,
  },
  content: {
    padding: 20,
    paddingBottom: 36,
  },
  header: {
    marginBottom: 18,
  },
  backButton: {
    width: 36,
    height: 36,
    borderRadius: 999,
    backgroundColor: "rgba(255, 255, 255, 0.12)",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 12,
  },
  backButtonText: {
    fontSize: 22,
    color: stylesColors.cream,
    fontWeight: "700",
    includeFontPadding: false,
    textAlign: "center",
    textAlignVertical: "center",
    lineHeight: 22,
  },
  title: {
    fontSize: 28,
    fontWeight: "900",
    color: stylesColors.cream,
  },
  subtitle: {
    marginTop: 8,
    fontSize: 14,
    lineHeight: 20,
    color: "rgba(245, 236, 215, 0.72)",
  },
  heroCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    borderRadius: 24,
    padding: 18,
    backgroundColor: stylesColors.cardBg,
    marginBottom: 18,
    borderWidth: 1,
    borderColor: "rgba(245, 236, 215, 0.12)",
  },
  heroIcon: {
    fontSize: 34,
  },
  heroTextBlock: {
    flex: 1,
  },
  heroTitle: {
    color: stylesColors.cream,
    fontSize: 18,
    fontWeight: "900",
    marginBottom: 6,
  },
  heroDescription: {
    color: "rgba(245, 236, 215, 0.82)",
    lineHeight: 20,
  },
  sectionHeader: {
    marginBottom: 12,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "900",
    color: stylesColors.cream,
  },
  card: {
    backgroundColor: stylesColors.cream,
    borderRadius: 24,
    padding: 16,
    marginBottom: 12,
  },
  cardTopRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  iconBubble: {
    width: 52,
    height: 52,
    borderRadius: 18,
    backgroundColor: stylesColors.wine,
    alignItems: "center",
    justifyContent: "center",
  },
  iconText: {
    fontSize: 24,
  },
  cardHeaderText: {
    flex: 1,
  },
  cardTitle: {
    fontSize: 16,
    fontWeight: "900",
    color: "#2A1F24",
    marginBottom: 4,
  },
  cardDescription: {
    fontSize: 13,
    lineHeight: 19,
    color: "#5E4F55",
  },
  logoutCard: {
    backgroundColor: stylesColors.cream,
    borderRadius: 24,
    padding: 16,
    marginTop: 4,
    marginBottom: 24,
    gap: 14,
  },
  logoutTextBlock: {
    gap: 4,
  },
  logoutTitle: {
    fontSize: 16,
    fontWeight: "900",
    color: "#2A1F24",
  },
  logoutDescription: {
    fontSize: 13,
    lineHeight: 19,
    color: "#5E4F55",
  },
  logoutButton: {
    minHeight: 46,
    borderRadius: 999,
    backgroundColor: stylesColors.wine,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 20,
  },
  logoutButtonText: {
    color: stylesColors.cream,
    fontWeight: "900",
    fontSize: 14,
    textAlign: "center",
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.45)",
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  modalCard: {
    width: "100%",
    maxWidth: 340,
    borderRadius: 24,
    backgroundColor: "#fff",
    paddingVertical: 28,
    paddingHorizontal: 22,
    alignItems: "center",
  },
  modalIcon: {
    fontSize: 30,
    marginBottom: 12,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: "900",
    color: "#2A1F24",
    textAlign: "center",
  },
  modalMessage: {
    marginTop: 8,
    fontSize: 14,
    lineHeight: 21,
    color: "#5E4F55",
    textAlign: "center",
  },
  modalButtonRow: {
    flexDirection: "row",
    gap: 10,
    marginTop: 20,
    width: "100%",
  },
  modalSecondaryButton: {
    flex: 1,
    minHeight: 46,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: stylesColors.wine,
    alignItems: "center",
    justifyContent: "center",
  },
  modalSecondaryButtonText: {
    color: stylesColors.wine,
    fontWeight: "900",
    fontSize: 14,
  },
  modalPrimaryButton: {
    flex: 1,
    minHeight: 46,
    borderRadius: 999,
    backgroundColor: stylesColors.wine,
    alignItems: "center",
    justifyContent: "center",
  },
  modalPrimaryButtonText: {
    color: stylesColors.cream,
    fontWeight: "900",
    fontSize: 14,
  },
  feedbackCard: {
    width: "100%",
    maxWidth: 320,
    borderRadius: 24,
    backgroundColor: "#fff",
    paddingVertical: 26,
    paddingHorizontal: 22,
    alignItems: "center",
  },
  feedbackIcon: {
    width: 56,
    height: 56,
    borderRadius: 999,
    backgroundColor: "rgba(123, 30, 46, 0.12)",
    color: stylesColors.wine,
    textAlign: "center",
    textAlignVertical: "center",
    fontSize: 28,
    fontWeight: "900",
    marginBottom: 14,
    overflow: "hidden",
  },
  feedbackTitle: {
    fontSize: 18,
    fontWeight: "900",
    color: "#2A1F24",
    textAlign: "center",
  },
  feedbackButton: {
    marginTop: 18,
    minWidth: 120,
    minHeight: 46,
    borderRadius: 999,
    backgroundColor: stylesColors.wine,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 20,
  },
  feedbackButtonText: {
    color: stylesColors.cream,
    fontWeight: "900",
    fontSize: 14,
  },
});
